### ISSUE TITLE
Revisit Options Order

### ISSUE THREAD

**Issue by HaoK** [aspnet/Options#1]
1.The default implementation for option accessor and option setups seems to prevent scoped option setups from working. I believe these more dynamic scenarios are important and not necessarily exclusive to data.
 2.I think it would be good to have a nice pattern to register option setups that override or not override other option setups, i.e. the issue of specifying the "Order" of the IOptionsSetup. Hao proposed using a flag, which I am ok with trying. Not sure it will make it to this checking though.
 3.The implementation of binding to keys from configuration to matching properties on TOptions only work with core and desktop .NET and I haven't got a good answer on whether this can be addressed.

**Comment by muratg** [comment]
@HaoK do we still need this? Putting into backlog for now to remove it from triage list.

**Comment by divega** [comment]
Yes, I think we should revisit this soon.

**Comment by divega** [comment]
@lodejard, @kirthik and @HaoK met today and we agreed it would be good to get rid of explicit ordering for the application of `IConfigurations<TOptions>`. Instead you will get the order or registration in DI. Before we go ahead removing it we need to look at how it is being used in the frameworks (in particular in MVC) and makes sure the same behavior can be achieved.

**Comment by HaoK** [comment]
Nuked order from Options.
