### ISSUE TITLE
Middleware pattern for IOptions<T>

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Options#105]
Given the below middleware definition, there are various scenarios that we can support:

```C#
namespace MyMiddleware
{
    public class FooMiddleware
    {
        public FooMiddleware(RequestDelegate next, IOptions<FooOptions> options)
        {
        }
    }
}
```

### A - case: Foo component graph gets IOptions<FooOptions> somewhere other than middleware (example MVC)

```C#
using MyMiddleware;

namespace Microsoft.AspNet.Builder
{
    public class FooOptions 
    {
        public int Value { get; }
    }

    public class FooMiddlewareExtensions
    {
        public static IApplicationBuilder UseFoo(this IApplicationBuilder app)
        {
            return app.Use<FooMiddleware>();
        }
    }

   public class BarService
   {
      public class BarService(IOptions<FooOptions> options) { }
   }
}
```

### B - case: Only Middleware class gets IOptions<FooOptions>

```C#
using MyMiddleware;

namespace Microsoft.AspNet.Builder
{
    public class FooOptions
    {
        public int Value { get; }
    }

    public class FooMiddlewareExtensions
    {
        public static IApplicationBuilder UseFoo(this IApplicationBuilder app)
        {
            return app.Use<FooMiddleware>();
        }

        public static IApplicationBuilder UseFoo(this IApplicationBuilder app, FooOptions options)
        {
            return app.Use<FooMiddleware>(Options.Create(options));
        }
    }
}
```

### 1 - Configure options for middleware from DI

```C#
public class Startup
{
    public void ConfigureServices(IServiceCollection services)
    {
        // DI scenario
        services.Configure<FooOptions>(options => 
        {
            options.Value = 10;
        });
    }

    public void Configure(IApplicationBuilder app)
    {
        // Get the options for Foo from IOC
        app.UseFoo();
    }
}
```

### 2 - Use Foo without adding services/options (get it from the DI container if it's configured)

```C#
public class Startup
{
    public void Configure(IApplicationBuilder app)
    {
        app.UseFoo();
    }
}
```

### 3 - Using a specific instance of options that will only apply to the specific middleware

```C#
public class Startup
{
    public void Configure(IApplicationBuilder app)
    {
        // Directly configure the middleware
        app.UseFoo(new FooOptions
        {
            Value = 10;
        });
    }
}

```

- The namespace for options classes and the extension methods are `Microsoft.AspNet.Builder`
- We're moving away from lambdas because when specified on the middleware itself, it doesn't compose the same way that it does when configuring it via services.

**Comment by PinpointTownes** [comment]
![image](https://cloud.githubusercontent.com/assets/6998306/12105265/443f168c-b353-11e5-880b-cb0887e9d297.png)

So...

Concerning the `ConfigureServices() + app.UseExtension()` pattern: personally, I like it (mainly as it makes creating per-environment options easy), but it doesn't play nicely when having multiple instances of the same middleware and might be a terrible trap for beginners (specially if there's no support for named options). It's definitely something to keep in mind before adopting it.

_______

```csharp
public class FooOptions : IOptions<FooOptions>
{
    public int Value { get; }

    FooOptions IOptions<FooOptions>.Options { get { return this; } }
}
```

Having to implement `IOptions<>` everywhere to return `this` is just **horrible**: [people will necessarily end up injecting the options instance in the DI container instead of relying on the options stack] (http://stackoverflow.com/a/31405021/542757). An `IOptions<>` wrapper would be a much nicer approach: https://github.com/aspnet/Options/issues/78#issuecomment-127441235.

_______

> We're moving away from lambdas because when specified on the middleware itself, it doesn't compose the same way that it does when configuring it via services.

Really sad decision. The delegate syntax offers a much more flexible approach:
  * It allows setting "default" values before invoking the delegate, while still allowing the developer to override them (call that local composition if you want):

```csharp
// app.UseOpenIdConnectServer automatically sets AllowInsecureHttp
// to true on development or testing environments before invoking the delegate.
app.UseOpenIdConnectServer(options => {
    options.AllowInsecureHttp = false;
});
```

  * It allows defining and using extensions methods directly on the options:

```csharp
app.UseOpenIdConnectServer(options => {
    options.UseJwtTokens();
});
```

  * Working with collections properties is much easier with the delegate approach:

```csharp
app.UseOpenIdConnectAuthentication(options => {
    // Remove the default scopes.
    options.Scope.Clear();
    options.Scope.Add("custom");
});
```

**Comment by davidfowl** [comment]
I like the `Options<T>` poco wrapper, it does clean up the ugly hack around making the type implement the options itself.

**Comment by davidfowl** [comment]
More data https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/145

**Comment by HaoK** [comment]
I think maybe we can just add sugar in Options.Create to reenable the lambda...

```
  app.UseCookiesAuthentication(Options.Create<CookiesAuthenticationOptions>(o => o.AuthenticationScheme = "No!"))
```

**Comment by davidfowl** [comment]
One thing @PinpointTownes was doing in his middleware was setting defaults in the extension method (which I personally think is in the wrong place). It should be pushed down to the middleware ctor where possible. The extension method should do as little as it can.

**Comment by HaoK** [comment]
Yeah I think we can live without 'local' composition.  But I definitely agree with him about the second two points.  When I was working on the security middleware, I tried it first without the lambdas overload and it was gross, so I added it back :)

**Comment by davidfowl** [comment]
Lets write out the samples and compare them side by side. I agree to some extent but it would be great to eye ball them next to each other.

**Comment by HaoK** [comment]
Fair enough, the changes for the Security repo changes will be a good eye ball example to look at.  The social sample apps specifically has a ton of options that get configured...

**Comment by PinpointTownes** [comment]
> It should be pushed down to the middleware ctor where possible. The extension method should do as little as it can.

All the default values are set from the options class itself (using some C# 6 love :smile:), but this one requires `IHostingEnvironment`, which needs to be resolved from the services container.

**Comment by JunTaoLuo** [comment]
Take a look at https://github.com/aspnet/Security/pull/646

**Comment by HaoK** [comment]
Maybe I am crazy, but I still like the thought of being able to configure the middleware pipeline  as Options

```
// No longer need Services suffix since we only have one method
public void Configure(IServiceCollection services) {
    services.Configure<FooOptions>(options => options.FooIsGood = true);
    
    // sugar for services.Configure<WebApplicationPipelineOptions>
    services.ConfigureApp(app => {  
        app.UseFoo();
        app.UseBar();
    }
}

public WebApplicationPipelineOptions {
   Action<IApplicationBuilder> Configure { get; set; }
}
```

We could still look for a Startup `Configure(IApplicationBuilder)` which would override the options...

**Comment by davidfowl** [comment]
That's soon not going to happen at this point (I don't even like it 😀)

**Comment by JunTaoLuo** [comment]
All middleware have been updated now. Closing

**Comment by leastprivilege** [comment]
I actually liked the Action<Option> approach just from a coding point of view because you didn't need to add a using statement for the options class. 

The solution of putting the options class into the builder namespace to avoid that is just wrong IMO.

**Comment by davidfowl** [comment]
> I actually liked the Action approach just from a coding point of view because you didn't need to add a using statement for the options class.

We just found that exposing `Action<T>` having the same pattern as `services.Configure<T>` was misleading because those options do not compose with ones registered in the DI system.

> The solution of putting the options class into the builder namespace to avoid that is just wrong IMO.

Eh, its similar to putting extension methods in the builder namespace. They're likely *never* going to be used outside of the middleware itself and the startup class.

**Comment by PinpointTownes** [comment]
What's fun is that you had at least 4 strong reasons not to make this change and only one to make it: a very hypothetical misleading risk that nobody has ever complained about :smile:

**Comment by davidfowl** [comment]
> a very hypothetical misleading risk that nobody has ever complained about 

That and the fact that sometimes you want to actually control the instance being created (because maybe it's coming from somewhere else). Meaning that you'd need at least 2 overloads if we always wanted to have both the delegate pattern and the pattern that allows passing an instance. Then you have to explain that we have these overloads because they are "nice" :smile:
