### ISSUE TITLE
Add Options<T>

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Options#106]
Would act as an `IOptions<T>` wrapper for some T. Would make a convenient way to create an `IOptions<T>` from any T. We could also have a factory method (/cc @divega) that makes one of these from a T i.e. `IOptions<T> Options.Create<T>(T options)`.

**Comment by HaoK** [comment]
Would this would be instead of the old pattern of MyOptions implementing `IOptions<MyOptions>`?

**Comment by davidfowl** [comment]
Yep! It's something @PinpointTownes suggested https://github.com/aspnet/Options/issues/105#issuecomment-168866368.

**Comment by davidfowl** [comment]
I updated the sample in B to show the usage.

**Comment by HaoK** [comment]
Ok yeah that looks much better, it was pretty gross making everything implement IOptions before...  Maybe we should name the generic Options class OptionsWrapper so people don't think its a base class...which is what the name implies...

**Comment by davidfowl** [comment]
PR out for review.

**Comment by HaoK** [comment]
Do we want to consider an overload of `Options.Create<T>(Action<T> configure)` just as pure sugar?

**Comment by davidfowl** [comment]
Hmmmmmmmm

**Comment by davidfowl** [comment]
```C#
app.UseFoo(Options.Create(options =>
{
    options.Value = 10;
});
```

```C#
var options = Options.Create(opt =>
{
  opt.Value = 10;
});

app.UseFoo(options);
```

**Comment by HaoK** [comment]
Yeah well this way you give people the option to do either one, so everyone is happy
