### ISSUE TITLE
Syntax sugar for Func/Delegate/Type

### ISSUE THREAD

**Issue by HaoK** [aspnet/Options#11]
Syntax sugar would be specifically to have a value-type that can be used as options.Notification to hold the delegate, and also to hold onto the delegate.

**Comment by PinpointTownes** [comment]
@HaoK any progress concerning this (essential) feature? :smile:

**Comment by HaoK** [comment]
With named options going away, we could use this in place of IOptions for middleware, maybe something like:

```
public class Box<TService> {
   public Box(TService instance) { _instance = instance; }
   public Box(Func<TService> factory); { _factory = factory; }

   public void Initialize(IServiceProvider services);

   public TService Value {
     return _instance ?? _factory?.Invoke() ?? _services?.GetRequiredService<TService>();
   }
}

public class XyzMiddleware {
   public XyzMiddleware(Box<XyzOptions> options) { Options = options.Value }
}

app.UseMiddleware<XyzMiddleware>(new Box(xyzOptions)); // use instance
app.UseMiddleware<XyzMiddleware>(new Boxy(() => new XyzOptions())); // factory delegate
app.UseMiddleware<XyzMiddleware>(); // use whatevers in DI 

I'll also have to update the TypeActivator to special case Box parameters, and call Initialize with the ISP
```

Thoughts? @divega @lodejard @Tratcher @davidfowl

**Comment by HaoK** [comment]
Instead we can just make `MyOptions : IOptions<MyOptions>` and accomplish this without the Box

**Comment by HaoK** [comment]
Sounds like this is no longer needed with the direction we went making Options implement IOptions

**Comment by PinpointTownes** [comment]
> Sounds like this is no longer needed with the direction we went making Options implement IOptions

Do you have a sample demonstrating how it works concretely?

A typical case is when you want to replace the default notifications class with a new class where you need to inject per-scoped things like a `DbContext`.

```csharp
public class MyOAuthBearerAuthenticationNotifications : OAuthBearerAuthenticationNotifications {
    public MyOAuthBearerAuthenticationNotifications(DbContext context) {
        SecurityTokenReceived = async notification => { [validate the token with a DB call] };
    }
}

**Comment by PinpointTownes** [comment]
Still no official plan for DI-enabled events classes?

Related topic: https://github.com/aspnet-contrib/AspNet.Security.OpenIdConnect.Server/issues/275

/cc @ilmax
