### ISSUE TITLE
Add doc comments for service collection extension methods

### ISSUE THREAD

**Issue by Eilon** [aspnet/Options#118]
At least these classes and methods:
* https://github.com/aspnet/Options/blob/dev/src/Microsoft.Extensions.Options/OptionsServiceCollectionExtensions.cs
* https://github.com/aspnet/Options/blob/dev/src/Microsoft.Extensions.Options.ConfigurationExtensions/OptionsServiceCollectionExtensions.cs

Recommend following the general pattern we've used in other places, e.g. https://github.com/aspnet/Session/blob/dev/src/Microsoft.AspNetCore.Session/SessionServiceCollectionExtensions.cs

**Comment by HaoK** [comment]
b4a9c2014c8eb567738cd170a3bee3fea7bfadc7
