### ISSUE TITLE
Why no Microsoft.Extensions.Options.Abstractions?

### ISSUE THREAD

**Issue by cwe1ss** [aspnet/Options#120]
Hi,

I was wondering why the packages in this project are structured the way they are and not like this:

* `Microsoft.Extensions.Options.Abstractions`: contains `IOptions` and so on - this package will be used by other libraries who just want to get IOptions injected and has no dependencies.
* `Microsoft.Extensions.Options`: This package contains everything else from the existing package and from `Microsoft.Extensions.Options.ConfigurationExtensions`. This package would be used e.g. by asp.net projects who want to configure the Options.

Wouldn't this better reflect how other Extensions-libraries are structured? (Logging, DependencyInjection, ...).

Thanks for clarification and best regards!

**Comment by davidfowl** [comment]
+1

/cc @Eilon @divega @HaoK

**Comment by herecydev** [comment]
This was mentioned [here](https://github.com/aspnet/Options/pull/116#issuecomment-184533932). There isn't a great deal to the Options but I guess it doesn't hurt. I'm in favor of it :+1:

**Comment by divega** [comment]
I am in favor too.

@HaoK @shirhatti let's discuss it in triage.

**Comment by herecydev** [comment]
@divega Wouldn't the outcome of [this](https://github.com/aspnet/Options/issues/116) have a large say in whether this is necessary or not.

**Comment by divega** [comment]
Yes, because if we agreed that the contents of the PR is what we want then `IOptions<T>` wouldn't be necessary any more for consuming options. However many library that consume options would probably still need to depend on Options to register them in the service collection. We'll see where we land.

**Comment by divega** [comment]
We tried this, but in the end we found very little value in separating Options into abstractions and implementation. We have already separated ConfigurationExtensions into its own package which means packages which depend from Options don't depend on Configuration, which is nice.

For more details on the reasons we are closing this you can look at the discussion in the PR at https://github.com/aspnet/Options/pull/132. 

Feel free to reactivate or create a new issue if you are aware of better reasons to do this.
