### ISSUE TITLE
Removing IOptions<T>

### ISSUE THREAD

**Issue by HaoK** [aspnet/Options#122]
Summary of planned options changes:

1. Removing `IOptions<T>` entirely, Options must be registered as services (updating all middleware/frameworks)
2. `AddOptions<T>` sugar which registers an options as a singleton:

```
            services.AddSingleton(s => {
                var o = new OptionsHao();
                foreach (var c in s.GetRequiredService<IEnumerable<IConfigureOptions<OptionsHao>>>())
                    c.Configure(o);
                return o;
            });
```
3.  Our framework options will not use this sugar, but will switch to ctor's taking `IEnumerable<IConfigureOptions<T>>` (with potentially a new base Options<T> class)

cc @divega @lodejard @davidfowl

**Comment by leastprivilege** [comment]
finally.

**Comment by davidfowl** [comment]
One thing I don't want to lose: The ability for middleware get a default `TOptions` when nothing is specified. That is one advantage of having a default `IOptions<TOptions>` available in the container.

**Comment by HaoK** [comment]
Hrm, that's definitely an issue right now.  

Does making options the last parameter and optional work?

```C#
  public Middleware(Foo f, MyOptions options = null) {
    _options = options ?? new MyOptions();
  }
```

**Comment by PinpointTownes** [comment]
> One thing I don't want to lose: The ability for middleware get a default TOptions when nothing is specified. That is one advantage of having a default IOptions<TOptions> available in the container.

:+1:

**Comment by matthewDDennis** [comment]
I think; this and discussions in #116 show that the DI system is missing an important feature.  Many DI containers are able to resolve concrete classes, even if they have not been registered in the container.  Having done this in Munq, and having a quick look at the DI code, it shouldn't be a difficult task to add this feature.  All the hard parts are already done. Just need to create a factory method for the class if it does not exist in the resolved classes, and register it.

By default, the class would be resolved Transient, but could be explicitly registered for other lifetimes.

I'll take a look and see if I can put together a pull request for the DI container.

**Comment by davidfowl** [comment]
> Many DI containers are able to resolve concrete classes, even if they have not been registered in the container.

How many? The top 10 (if there are that many)? That's not something we want to do by default in all cases anyways. In the cases where we need control over what things come from DI and what things don't, we manually type activate.

> Having done this in Munq, and having a quick look at the DI code, it shouldn't be a difficult task to add this feature.

We don't add new features to DI lightly. Not to mention that's it's a bit late to be adding features like this without measuring the effect it will have on our entire stack.

> I'll take a look and see if I can put together a pull request for the DI container.

File an issue, don't send a PR.

**Comment by lodejard** [comment]
@haok I don't think we have verified =null is supported on all of the containers we're compatible with. An alternative would be to have two ctors on the middleware and double checking the shorter one is called only when options aren't available?

**Comment by HaoK** [comment]
@lodejard I verified that your approach works, so we should be good by just adding ctor overloads to any middleware that wish to support a default options.

Should we also consider revisiting many of our options classes that currently initialize default worker/providers and having them pull them as services instead, namely ClaimsTransformation/Auth/Identity could all do this via overloaded ctors similar to the workaround for middleware to set defaults...

See https://github.com/aspnet/Security/issues/591 for the issue which we can finally address

For example:
```
   // No default overload for ClaimsTransformation since we probably want that to be an error if
   // ClaimsTransformation was requested but none was specified
   public class ClaimsTransformationOptions {
      public ClaimsTransformationOptions(IClaimsTransformer transform) {
         _transform = transform;
      }
   }

   // Auth would pull new appropriate events for each auth middleware
   public class GoogleAuthenticationOptions {
      public GoogleAuthenticationOptions() : this(new GoogleEvents(), new SystemClock()) { }
      public GoogleAuthenticationOptions(IGoogleEvents events, ISystemClock clock) {
          _events = events;
          _clock = clock;
      }
   }
```

**Comment by PinpointTownes** [comment]
> @lodejard I verified that your approach works, so we should be good by just adding ctor overloads to any middleware that wish to support a default options.

Good to know. So it works with all the well-known providers? (Autofac, StructureMap, Ninject, Castle Windsor, Unity...)

**Comment by HaoK** [comment]
@PinpointTownes Oh no, I just verified that our DI system works to resolve the shorter ctor when Options service is missing.  I assumed (perhaps mistakenly) that this behavior could be relied upon...

**Comment by PinpointTownes** [comment]
Personally, I'd test with at least Autofac and StructureMap. You could have a nasty surprise :smile:

**Comment by HaoK** [comment]
I think this is covered by our DI spec test here: which says that the container must pick the ctor with the longest match

https://github.com/aspnet/DependencyInjection/blob/dev/src/Microsoft.Extensions.DependencyInjection.Specification.Tests/DependencyInjectionSpecificationTests.cs#L590

**Comment by davidfowl** [comment]
Hmm, one more thing I think might be affected. Since there's no default `IOptions<TOptions>` in the container, random things can't ask for `TOptions` without making sure it has been registered first... I don't know if we try to get `IOptions<TOptions>` anywhere we don't already have an extension method on `IServiceCollection` that calls `AddOptions()`

**Comment by HaoK** [comment]
Oh trust me I hit this scenario already, there's about 500 tests I've been updating just in MVC that are doing exactly this...

**Comment by HaoK** [comment]
But I'm not sure how common it is for things other than unit tests to not explicitly calling AddMvc

**Comment by HaoK** [comment]
Chatted with @lodejard and we have updated the proposal a bit:

- Introduce a new `IOptionsInitializer<T>` service that handles basically maps `IEnumerable<IConfigureOptions<T>>`.  AddOptions() will rename in hosting and Add this service.

- Don't `AddOptions<T>` sugar, and standardize on this single pattern.  The delegeate/singleton would still work, but we won't add the sugar so we avoid the messaging problem.

- New Proposed Options ctor pattern will look like this:
```C#
  public class MyOptions {
    public MyOptions {
       Setting = "DefaultValue";
    }
    
    public MyOptions(IOptionsInitializer<T> initializer) : this() {
        initailizer.Initialize(this);
    }
  }
```

- Finally rename `IConfigureOptions<T>` => `IOptionsConfiguration<T>`

**Comment by HaoK** [comment]
Decided against making this change

**Comment by khellang** [comment]
> I think this is covered by our DI spec test here: which says that the container must pick the ctor with the longest match

FYI; we had to introduce a custom behavior in the StructureMap constructor selection to pass those tests. Can any of you expand on why that behavior was chosen? Is there anything relying on it right now?

**Comment by davidfowl** [comment]
@khellang hmmmm, not sure.

/cc @pranavkm @lodejard any ideas why this was added?

**Comment by pranavkm** [comment]
https://github.com/aspnet/DependencyInjection/issues/69 was the basis for adding that feature. I suggested using this behavior in a recent feature that @sebastienros was working on, but I'm not super sure if there's actual code that relies on this behavior.

**Comment by pranavkm** [comment]
https://github.com/aspnet/HttpAbstractions/blob/dev/src/Microsoft.AspNetCore.Http/HttpContextFactory.cs#L12 uses this behavior. I guess any service type with multiple public ctors is suspect here.

**Comment by davidfowl** [comment]
Multiple ctors most containers can handle that, I think @khellang meant optional parameters.

**Comment by davidfowl** [comment]
Or not, https://github.com/structuremap/structuremap.dnx/blob/master/src/StructureMap.Dnx/ContainerExtensions.cs#L34 :smile:

**Comment by khellang** [comment]
Yeah, it wasn't a big change for StructureMap, and fortunately it already supports pluggable ctor selection strategies :smile: By default, SM selects the constructor solely based on the number of parameters (filtered on primitive types).

With the current behavior, it could pick a different constructor depending on how the container is configured, which can lead to some subtle bugs. Is this really the best default?
