### ISSUE TITLE
Consider renaming IConfgureOptions and related types

### ISSUE THREAD

**Issue by divega** [aspnet/Options#127]
This is to capture some possibly good naming changes that were suggested during the prototyping of "options as services". The PR is now closed but [feedback was provided that some of these name changes were good](https://github.com/aspnet/Options/pull/124#issuecomment-192047332), e.g. 

``` C#
IConfigureOptions  ->  IOptionsConfiguration  or  IOptionsSetup 
ConfigureOptions  ->  OptionsConfiguration  or  OptionsSetup 
```

**Comment by PinpointTownes** [comment]
@shirhatti when closing a ticket, it's always useful to mention *why* you're doing that.
IMHO, renaming the weird `IConfigureOptions` and `ConfigureOptions` should be done before it's too late.

**Comment by divega** [comment]
@PinpointTownes when we discussed this in triage the majority of people present thought these names were not great but didn't matter too much...  It would be really good to hear from you why you think they do matter.

**Comment by PinpointTownes** [comment]
I guess I'm probably nitpicking, but I think having verbs in an interface/class name is a bit weird, specially here were IOptionsConfiguration would be much more elegant.

**Comment by divega** [comment]
@PinpointTownes The argument was more about the interface and class name not being too exposed to most customers (you really only use the `Configure<TOptions>`() extension method unless you are implementing a custom `IConfigureOptions<TOptions>`, which is considered an advanced scenario) and the cost of making a breaking change across repos. 

Feel free to counter that :smile:

**Comment by PinpointTownes** [comment]
> The argument was more about the interface and class name not being too exposed to most customers

`[EditorBrowsable(EditorBrowsableState.Never)]`? :trollface: 

Honestly, I won't fight for this change. `(I)ConfigureOptions` has a weird (and inconsistent) name, but it doesn't affect its functionalities, so I'm fine :smile:
