### ISSUE TITLE
How do we read interface objects/inherited objects?

### ISSUE THREAD

**Issue by shederman** [aspnet/Options#131]
If I have options like:

```
public class MyOptions {
    Collection<IRule> Rules { get; set; }
}
```

How do I write the JSON so that it tells the options system to read the relevant subtype?

**Comment by shirhatti** [comment]
This is not supported.

Options rely on `Configuration.Binder` which doesn't support polymorphism.

**Comment by shederman** [comment]
So there's no way to have complex settings in appsettings.json?

In other words we should stick to xml configs for real world systems?
