### ISSUE TITLE
Microsoft.Extensions.Options 1.0.0-rc3-20903 -DNX support

### ISSUE THREAD

**Issue by josin** [aspnet/Options#140]
I'm trying to build my project but I'm getting following error:

```
The dependency Microsoft.Extensions.Options 1.0.0-rc3-20903 in project xyz does not support framework DNX,Version=v4.5.1.
```

My full list of dependencies is following:
```
"dependencies": {
    "Microsoft.AspNet.Mvc.Core": "6.0.0-rc1-final",
    "Microsoft.AspNet.Mvc.ViewFeatures": "6.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Abstractions": "1.0.0-rc1-final",
    "Microsoft.Extensions.DependencyInjection.Abstractions": "1.0.0-rc1-final",
    "Microsoft.Extensions.Primitives": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Abstractions": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
    "Microsoft.Net.Http.Headers": "1.0.0-rc1-final",
    "Microsoft.Extensions.Options": "1.0.0-rc3-*",
    "Swashbuckle": "6.0.0-rc1-final",
    "Microsoft.AspNet.SignalR.Server": "3.0.0-rc2-*"
  },

  "frameworks": {
    "dnx451": {
    }
  },
```

Do you know guys if there is any way how to fix that issue?

Thank you,
Josef

**Comment by cwe1ss** [comment]
For RC1 you have to use `"Microsoft.Extensions.OptionsModel": "1.0.0-rc1-final"` instead of `Microsoft.Extensions.Options`. This is [a breaking change from RC1 to RC2](https://github.com/aspnet/Announcements/issues/132).

**Comment by cwe1ss** [comment]
And I'm not sure if SignalR will work as this also points to a non RC1-version. SignalR will not be done for V1 so I'm not sure if there even is a compatible package.

**Comment by josin** [comment]
Thank you very much for your answer. Result is such that project compiles and that's great success :-) I'll see what I can do with SignalR, my integration with this lib is still in early stages...

**Comment by BrennanConroy** [comment]
Also, highly recommend using just RC1 or just RC2 or just RC3, mixing them all together is a bad idea.
