### ISSUE TITLE
Change tracking not working

### ISSUE THREAD

**Issue by cesarbs** [aspnet/Options#141]
I have the following config JSON file:

    {
      "SomeOptions": {
        "AnOption": "a config value",
        "AnotherOption": 42
      }
    }

I use it in my app (with change tracking) via:

    services.AddOptions();
    services.Configure<MyOptions>(Configuration.GetSection("SomeOptions"), true);

Where `Configuration` is:

    Configuration = new ConfigurationBuilder()
        .SetBasePath(env.ContentRootPath)
        .AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
        .Build();

When I change `appsettings.json` while the app is running, the changes are not reflected in my app.

**Comment by divega** [comment]
@cesarbs can you add a snippet of how you are consuming the options?

**Comment by cesarbs** [comment]
@divega Sure. I tried two different things. One is the same as here: https://docs.asp.net/en/latest/fundamentals/configuration.html#using-options-and-configuration-objects

The other is a non-MVC app:

    public void Configure(
        IApplicationBuilder app,
        IOptions<MyOptions> myOptionsAccessor)
    {
        var myOptions = myOptionsAccessor.Value;

        app.Run(async (context) =>
        {
            await context.Response.WriteAsync($"An option: {myOptions.AnOption}");
            await context.Response.WriteAsync(Environment.NewLine);
            await context.Response.WriteAsync($"Another option: {myOptions.AnotherOption}");
        });
    }

Is it not updating because it creates a new instance whenever there is a change?

**Comment by cesarbs** [comment]
BTW I can make it work if I manually use an `IOptionsMonitor<>`:

    optionsMonitor.OnChange(opts =>
    {
        myOptions = opts;
    });

Is this how it's done by design? I thought the monitoring would happen automatically with

    services.Configure<MyOptions>(Configuration.GetSection("SomeOptions"), true);

**Comment by HaoK** [comment]
Yeah this is by design, change tracking is done push(the callback OnChange), or by pulling from the `IOptionsMonitor` current Value property.  The instance is never updated automatically.

**Comment by divega** [comment]
I believe there is possibly a tweak that would make it less confusing still. Let's chat about it in triage.

**Comment by Eilon** [comment]
@divega and I chatted about this earlier today. It's up to the *consumer* of `IOptions` to decide whether it wishes to work with modified options or not. It is never the choice of the *producer*.

**Comment by divega** [comment]
There are still minor tweaks that might help, e.g. currently we use several different terms to refer to the ability to track/monitor for and reload on changes, in parameters,  type names and even when we talk about the feature :smile:. If we could settle on one of those names in all places we could probably more easily funnel users to the right consuming pattern.

**Comment by shirhatti** [comment]
https://github.com/aspnet/Configuration/issues/419
