### ISSUE TITLE
[Discussion] Removal of OptionsMonitor (ReloadableOptions) for 1.0.0

### ISSUE THREAD

**Issue by HaoK** [aspnet/Options#144]
We are moving this feature to a sample for 1.0.0, and will revisit this feature in 1.0.1, we weren't totally happy with the current state of it, and want to give it more time to bake.

Note, this does not affect configuration reload on file change or the logging usage of that feature.

**Comment by andrewlock** [comment]
I was just looking at this functionality, and I think I can see why it's been removed as I had great difficulty getting it to work with rc2, but I was wondering what the reasoning behind removing it was?

It seems like having a reload triggered by a configuration change will be a relatively common use case, especially given the pushing of the the Options pattern in the docs, as well as the `reloadOnChange` option on `FileConfigurationProvider`.

At the moment, it's pretty confusing I think to have the underlying `IConfigurationRoot` be updated while the `IOptions<values>` injected in to your controllers do not change.

**Comment by HaoK** [comment]
It wasn't so much removed as postponed to post 1.0.0 due to lack of time.  We weren't satisfied with shipping it in its current state and wanted to make sure we had enough time to give it the proper attention before shipping it.

**Comment by Symbianx** [comment]
Is there any alternative for the OptionsMonitor with strongly typed options?

**Comment by jchannon** [comment]
I just hit the `reloadOnChange` issue not working in this scenario

```
              var builder = new ConfigurationBuilder()
                            .AddJsonFile("vqconsoleappsettings.json", optional:false, reloadOnChange:true)
                            .AddJsonFile("vqconsoleappsettings.dev.json", optional:true)
                            .SetBasePath(Path.GetDirectoryName(typeof(Program).GetTypeInfo().Assembly.Location));

            var config = builder.Build();

            var cfConfig = new ClassFactoryConfiguration();
            ConfigurationBinder.Bind(config, cfConfig);
```

If I have a loop and `Console.WriteLine(cfConfig.Blah);` and change the value of Blah in the json file I don't see the updated value.  

Are there plans to make this feature available?

**Comment by fleed** [comment]
I was trying to create a custom provider which updates the configuration on specific events, but the configuration was never changing.
Is it related to this issue? Is it considered for `1.1`, since `1.0.1` mentioned in the first post is already out?

**Comment by HaoK** [comment]
Updating configuration providers when configuration changes is not related options, did you derive from FileConfigurationProvider?  If not you would have to hook up something similar to get reload events

**Comment by fleed** [comment]
@HaoK I've derived from `ConfigurationProvider` because my provider doesn't have anything to do with files (it's based on `Redis publish/subscribe`), and invoked `this.OnReload()` method on updated.
Should I _copy_ other reload-related parts from `FileConfigurationProvider`?

**Comment by HaoK** [comment]
Calling `OnReload` will fire the reload token on your `IConfiguration`, do you have anything listening to that token?  Basically triggering that will call any callbacks you registered via `config.GetReloadToken().RegisterCallback(yourCallback)`

**Comment by HaoK** [comment]
OptionsMonitor is back in 1.1-preview1 acecacff57f9399e5871216a3f5a073548700dc3

**Comment by divega** [comment]
@Rick-Anderson as a heads up, this is a good topic to add in our 1.1 docs. E.g. we should probably start recommending customers to use `IOptionsSnapshot<TOptions>` almost identically to how the use `IOptions<TOptions>` today in per-request instances but with the advantage that they can get fresh values if the configuration changes.

**Comment by jchannon** [comment]
Does this address my issue?

**Comment by HaoK** [comment]
Yes you could use IOptionsMonitor to listen for changes

**Comment by pholly** [comment]
I just upgraded to 1.1 because I ran into the problem of my `IOptions<T>` classes not getting updated when underlying `appsettings.json` file changed (Thanks @andrewlock http://andrewlock.net/reloading-strongly-typed-options-when-appsettings-change-in-asp-net-core-rc2/). 

If I understand correctly, I need to change to `IOptionsSnapshot<TOptions>` to get the desired behavior of reloading on settings change. I have 47 places in my code that use `IOptions`. I wish there were a way to just configure `IOptions` to reload on appsettings change instead of having to change all 47 places. Is that possible? 

Could I just configure `IOptions` to be scoped instead of a singleton? So based on this: https://github.com/aspnet/Options/commit/acecacff57f9399e5871216a3f5a073548700dc3#diff-c783cfdb19a5ae3afb2dfd49f479c0a7R27 in my `Startup.cs` I would:
```services.AddScoped<IOptions<>, OptionsSnapshot<>>();```?

**Comment by divega** [comment]
@pholly It we would have been nice if `IOptions<T>` could just acquire this functionality automatically but we discussed this extensively and the team had concerns that it could cause subtle bugs in scenarios in which existing code could rely on the same singleton `IOptions<T>` to be returned every time it resolved it from DI. 

It is a done deal so my recommendation would be to just start using `IOptionsSnapshot<T>` where appropriate.

**Comment by pholly** [comment]
I think keeping the existing behavior would have been fine, but if we had the ability to configure `IOptions` to return `OptionsSnapshot` instead that would have been nice. Thanks for the explanation.
