### ISSUE TITLE
Don't rely on IoC containters to preserve registration order IConfigureOptions services

### ISSUE THREAD

**Issue by halter73** [aspnet/Options#150]
Autofac and possibly other IoC containers will not return IEnumerable resolved services in the order they were registered, but Options currently [depends on this behavior](https://github.com/aspnet/Options/blob/c7bff7184d3a3ab4074859b3fd3d36d83c474357/test/Microsoft.Extensions.Options.Test/OptionsTest.cs#L143). This causes certain extension methods in Kestrel, WebListener, MVC (and EF?) to break when Autofac is used.

This will probably require adding an `Order` property back to `IConfigureOptions` similar to what we had [back in beta7](https://github.com/aspnet/Options/blob/1.0.0-beta7/src/Microsoft.Framework.OptionsModel/IConfigureOptions.cs).

A key difference is we want to continue running the actions passed to [Configure](https://github.com/aspnet/Options/blob/4ef5a92054013f528d54ee3270501743f8d7e255/src/Microsoft.Extensions.Options/OptionsServiceCollectionExtensions.cs#L38) in the order they are added. This will likely require that `Configure` inspect the `IServiceCollection` prior to registering the `ConfigureOptions` instance.

This should resolve the issues raised in https://github.com/aspnet/Hosting/issues/785

**Comment by divega** [comment]
A few more details:
1. We should bring back the overloads of `Configure<T>()` that allow setting the order. 
2. When `Configure<T>()` inspects existing instances of `IConfigureOptions<T>` we should do (pseudo code) `1 + (setups.Any() ? setups.Max(s => s.Order) : 0)`. This works better for custom order than other options.
3. This will be a breaking change for any custom implementation of `IConfigureOptions<T>`, including our own in  https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Core/Internal/MvcCoreMvcOptionsSetup.cs and https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.WebApiCompatShim/WebApiCompatShimOptionsSetup.cs.

**Comment by HaoK** [comment]
We decided we are going to require IoC containters to preserve registration order
