### ISSUE TITLE
Reloadable options sample

### ISSUE THREAD

**Issue by divega** [aspnet/Options#156]
We should put together a simple sample showcasing recommended patterns for reloadable options so that we can reference it from places such the announcement at https://blogs.msdn.microsoft.com/webdev/2016/11/16/announcing-asp-net-core-1-1/.

**Comment by HaoK** [comment]
I'll put together some simple samples in a new samples directory in this repo, we won't be able to use MVC due to layering, but I don't think we really need to use MVC to demonstrate things clearly...  We'd have to put the sample somewhere like Entropy otherwise

**Comment by HaoK** [comment]
805e1f308c5f2212a0f83a086c7b94c7766fd228
