### ISSUE TITLE
Should Options 2.0 be async?

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Options#157]
I am currently writing an implementation that uses the database for option values. Have to do a `.Result`

**Comment by davidfowl** [comment]
Even if it was async it wouldn't help you. The caller would have to do .Result because application startup isn't async.

**Comment by sebastienros** [comment]
Let me create another issue then, where is the startup code?
And can we make `DisposeAsync()` too ;)

**Comment by davidfowl** [comment]
And async constructors

**Comment by davidfowl** [comment]
I think you're going to have to refactor your code to avoid doing async operations in ConfigureOptions.

**Comment by divega** [comment]
> I am currently writing an implementation that uses the database for option values

@sebastienros I would really like to understand why and I would appreciate if you could take a loot at https://github.com/aspnet/Configuration/issues/549 and shared your point of view. For sure we can chat in person if you want.

**Comment by sebastienros** [comment]
I'll take a look at this issue.

The idea is that the application exposes some screens to configure some settings and store these settings in the db. The middlewares that have to be configured use the `IOptions` pattern. To be able to use the service to load the values I need to use `IConfigureOptions`.

**Comment by HaoK** [comment]
So with the new Options 2.0 APIs, we have the ability to switch async in the new configures if we like...  Should we?

**Comment by HaoK** [comment]
Would make the core interfaces look something like:
```
  Task<TOptions> IOptionsService.GetAsync(string name);
  IServiceCollection.Configure(string name, Func<TOptions, Task> configureOption);
  with sugar for the sync overload
  services.Configure(string name, Action<TOptions> configureOptions) => services.Configure(name, o => {
      configureOptions(o);
      return Task.CompletedTask();
  });
```

**Comment by HaoK** [comment]
We decided against making options async for 2.0
