### ISSUE TITLE
Whole NETStandard.Library dependency

### ISSUE THREAD

**Issue by govorovvs** [aspnet/Options#158]
Do Microsoft.Extensions.Options 1.1.0 really needs the whole NETStandard.Library? Version 1.0.0 had dependencies to the few separate packages.

**Comment by davidfowl** [comment]
We've moved away from granular dependencies in general. Guidance is to use netstandard.library as a dependency minimally. In he future (netstandard 2.0) that will be the minimal reference (that can't be broken down into pieces)

**Comment by govorovvs** [comment]
I'm so upset. I use Options 1.1.0 package in WinForms .NET 4.6 project and my output directory looks awful. Microsoft started .NET Core with many good ideas (splitting into many packages, project.json, new build system), but now comes back to monolithic  netstandard.library, csproj and MSBuild.

**Comment by herecydev** [comment]
I'm hoping for a "prune" functionality that I heard was being talked about. Whilst I understand the reasons for moving to a baseline set of dependencies, it's not ideal when working with containers.

**Comment by davidfowl** [comment]
Thats not for libraries, just applications.

**Comment by herecydev** [comment]
That's fine then, libraries get the ease of development, applications get just what they need.
