### ISSUE TITLE
IOptionsMonitor inconsistency?

### ISSUE THREAD

**Issue by Shoshkin** [aspnet/Options#159]
While working with IOptionsMonitor with a number of file sources (Json,xml) , an inconsistency in the created object might occur if a change in some file config provider occurs in the same time as the ConfigurtionBinder binds the object due to change in another file config provider.

By inconsistency I mean that some props might be binded to the old values from the file while some to the new values.

Seems like no one mentions this point in any article written on this subject.

Am I missing something?
Is there any way to avoid this inconsistency while working with reload enabled?

**Comment by divega** [comment]
@Shoshkin you seem to be describing a race condition. I believe our current implementation lacks any safeguards to prevent the options from being partially bound or to deal with concurrent change token notifications. 

Any chance you could help us with a repro?

@HaoK @glennc I think we should discuss what it would take to make this more robust.

**Comment by glennc** [comment]
Adding it to 2.0.0, presumably we will do a run through of this milestone in Jan to determine if it actually fits.

**Comment by HaoK** [comment]
For 2.0, we moved away from monitoring changes/config reloads, and instead recompute IOptionsSnapshots every request, so this should no longer be an issue.

**Comment by HaoK** [comment]
We are likely going to remove OptionsMonitor in 2.0 since it was added for Snapshots which no longer require this behavior.
