### ISSUE TITLE
Revisit pattern of caching IOptions.Value / IOptionsSnapshot

### ISSUE THREAD

**Issue by HaoK** [aspnet/Options#163]
per @sebastienros today the pattern where we cache the value of the options in middleware everywhere prevents dynamically configuring options per tenants.  We should revisit this to see if this is something we should change.  As part of this we can also see if it makes sense to switch to IOptionsSnapshot anywhere.

**Comment by MaKCbIMKo** [comment]
Is there any news/ideas about caching pattern for Options? (https://github.com/aspnet/Options/issues/167)

**Comment by HaoK** [comment]
Might as well just use https://github.com/aspnet/Options/issues/161 to track revisiting any options patterns in 2.0
