### ISSUE TITLE
Rationalize IOptionsMonitor for Options 2.0

### ISSUE THREAD

**Issue by HaoK** [aspnet/Options#167]
With this change: https://github.com/aspnet/Options/pull/164  Snapshot no longer will be using the monitor logic at all, we can simplify our surface area by removing all of the monitor/change token related functionality since we no longer need it.

This would be a breaking change for consumers of IOptionsMonitor, but using the IOptionsSnapshot was the mainline scenario for reloadable options so that is unchanged.

**Comment by HaoK** [comment]
@glennc we should discuss this in triage

**Comment by MaKCbIMKo** [comment]
May I ask you what you decided to do with `OptionsMonitor`?

**Comment by dazinator** [comment]
If you remove the caching / monitoring, this will impact anyone who relies on that functionality. It's quite a common scenario not to want to load settings on every request (one cache them) and invalidate the cache only when changes are made imho. See 
https://github.com/aspnet/Options/issues/174

So if you do remove this, please offer people an alternative route to achieving this goal! I believe asp.net core has a caching library so imho it would be nice if all caching concerns could be delegated to that somehow!

**Comment by HaoK** [comment]
Yeah in 2.0 we should definitely look at make caching/lifetime of the options more pluggable in some way, so you'd be able to specify the lifetime of the options, and also do things like evictions/invalidations.

**Comment by flatproject** [comment]
In V2.0, IOptionsSnapshot will be scoped which means settings will be reloaded on every request. With this change it means that I will not be able to use it anymore in my project as  it will hit the database to reload around 800 settings on every request. So, the alternative for me is the IOptionsMonitor which provides the caching capability I'm looking for but it's more awkward to work with (Still haven't managed to reload settings from my custom database configuration provider)

If you are thinking of dropping IOptionsMonitor as this ticket suggests I would say at least make the IOptionsSnapshot to have a pluggable caching module (InMemory or Distributed or etc) with a configurable lifetime policy. Even better with an option to choose which configuration source to invalidate and reload instead of reloading the full configuration when you only want to invalidate and reload a small chunk of it from only a specific source.

**Comment by MaKCbIMKo** [comment]
I was thinking about how to integrate Options with [Caching](https://github.com/aspnet/Caching). We could build our solution based on `Caching.Abstraction` interfaces.

And probably, we will need to separate `Options.Abstractions` because Caching already uses Options (circular dependency?).

**Comment by HaoK** [comment]
Yeah caching will likely be part of the update to the PR https://github.com/aspnet/Options/pull/176 today.  Options.Abstractions would define the interface, if we wanted to add a Caching + OptionsCache implementation, that would live in a different package.

What I'm thinking for the next iteration of the PR right now:  

```C#
// Possibly fully async
interface IOptionsManager<TOptions> { // can be transient
  TOptions Value // Same behavior as IOptions.Value just with Validation applied 
  TOptions Get(string name); // Uses cache, creates a new instance if needed and validates via Validator
  void Add(string name, TOptions options); // Adds an externally created options to the cache
  bool Remove(string name); // removes the instance from the cache
}

interface IOptionsCache<TOptions> { // caching behavior plugability point (would be static in memory by default, but can be replaced by scoped ), 
  TOptions Get(string name);
  void Set(string name, TOptions options);
}

interface IOptionsValidator<TOptions> {
    ??? Validate(string name); // extensibility point for how validation actually done,
}
```

So I'm not sure if we need a snapshot, as that mimics to having a scoped IOptionsCache, but we might if we want to enable some different lifetimes for different options types (`IOptionsManager<SingletonOptions>` for static ones, and `IOptionsSnapshot<RequestOptions>`

Thoughts?

**Comment by MaKCbIMKo** [comment]
Not sure, that `IOptionsCache` need to be scoped.

I was thinking about how to use only one `IOptions` for injection, but somehow inject into IOptions instance cached and uncached versions of options provider (or Manager/Service). In that way we could configure caching on configuration level. But I need to more consideration and probably try to create a prototype. Still doubt about that.

**Comment by HaoK** [comment]
@dazinator @flatproject will the new `IOptionsService` with pluggable `IOptionsCache` in https://github.com/aspnet/Options/pull/176 be sufficient for you to use as a replacement for 1.1's IOptionsSnapshot functionality?

**Comment by dazinator** [comment]
@HaoK looks ok, so we would basically register our own `IOptionsCache<TOptions>` . One thing that seemed odd is that OptionsService has an add / remove method for adding / removing from the cache. Aren't those methods redundant, as people can consume IOptionsCache directly adding or removing from the cache..?

**Comment by dazinator** [comment]
I had a bit if a crazy idea that I'll mention! The setup / configure actions that can mutate an options instance and run in order. What if an action could stop subsequent actions from running. (A bit like short circuiting middleware). If that were possible, we could register the actions like so:

1st configure () checks fir cache. If exists then returns cached value and short circuits.
2nd configure() resolves from data source (i.e Json file or database etc) doesn't short circuit.
3rd configure () adds instance to cache.


This is a bit creative, but i think that would work and wouldn't require options to have any new caching interfaces.

**Comment by MaKCbIMKo** [comment]
Hm...I love the idea of having kinda middlewares for configuring an options (something like we do for appBuilder). That would allow to build chains of configurations (with branching by conditions). Moreover, that will make the order of applying these configurations much clear and transparent.

But all of these might be too complicated solution.

**Comment by HaoK** [comment]
Options already can be accessed and mutated from multiple threads today, as IOptions returns a shared singleton options to every request, and each request is able to manipulate the poco already.  The new stuff doesn't change that.  We do need to be careful to ensure that only one instance gets into the cache, which is why concurrent dictionary is used to be the gatekeeper.  But things should be ok assuming options manipulations are only done via Configures/Validates inside of the `Lazy<TOptions>` which is running all of the configure/validates inside of ConcurrentDictionary's AddOrGet.

**Comment by HaoK** [comment]
Also, its possible we will revert any changes we made to IOptionsSnapshot assuming the new IOptionsService covers the per request scenarios we were targeting with Snapshot.  No need for the breaking change if we are introducing a new surface area...

**Comment by HaoK** [comment]
Basically, `IOptionsService<ScopedOptions>` with a Scoped lifetime `IOptionsCache<ScopedOptions>` should be equivalent to the changes we made for IOptionsSnapshot in 2.0.

**Comment by HaoK** [comment]
@dazinator no shortcircuiting :)  The idea is all actions will always run, but there's nothing preventing the actions from checking an alreadyInitialized flag and becoming a no-op to roughly give you a short circuiting behavior where first Configure wins.  But that sounds like app specific functionality at that point...

**Comment by dazinator** [comment]
Ok cool. Would be nice to extend the fluent configuration / builder so that we could configure cache provided when setting up options in a fluent way. I had a look but i didn't see such a method yet, but would be good for discoverability!

**Comment by HaoK** [comment]
Not sure if there's any appropriate sugar, an overload of Configure that takes a OptionsCache and service lifetime seems super weird.  Its just normal service replacement, `services.AddScoped<IOptionsCache<>, MyOptionsCache<>>`

**Comment by dazinator** [comment]
Hmm yeah.. was just thinking if there was a `.UseCache<IOptionsCache<TOptions>>` method on the builder, you could get type inference on the `TOptions` type, and intellisense would provide the discoverability for cache configuration. Something like:


```
// Can't remember the actual API here but hopefully you get the gist! :-)

services.Configure<MyOptions>(fooSource).UseCache<MyCache>();

```

But I see how lifetime / service scope complicates that matter :-) you wouldn't want a different overload per possible registration scope!

Makes me wonder.. is it really necessary to have different lifetime scopes for IOptionsCache - for example can't it always be scoped to the request, and then any custom implementations can just have services from other scopes injected.. I.e the following custom options cache could be registered (with fluent method above) which would mean its scoped to the request, but it's `ISomeCacheService` could have a different scope based on user needs - i.e singleton:

```

public class MyOptionsCache : IOptionsCache<MyOptions>
{

public MyOptionsCache(ISomeCacheService cache service)
{

}

}
```

**Comment by dazinator** [comment]
How about if the sugar takes `IOptionsCache<TOptions>` where TOptions is inferred from `Configure<TOptions>` and it does the scoped registration for you? Just playing devil's advocate a bit, in that this would mean IOptionsCache would always be scoped, but I don't think that's a problem as a custom implementation could inject services from other scopes if required, or use a static backing field in their implementation for the cache state?

**Comment by MaKCbIMKo** [comment]
@HaoK @dazinator - I also was thinking about pretty the same API for registering cache for options:

```
services.Configure<TOptions>(foo).UseCache(); // use default implementation of cache
services.Configure<TOptions>(foo).UseCache<MyCache>(); // use custom implementation of cache
```

and probably:

```
// in case if can apply cache globally for all options
services.Configure<TOptions>(foo).UseNoCache();  // it will disable cache for options that we need
```

But still thinking about lifetime...

**Comment by dazinator** [comment]
RE: lifetime.. Could just always register IOptionsCache as scoped lifetime. Then any imementation could have any required services injected from other scopes if needed. For example the default implementation could just use a static backing field (concurrent dictionary) or have a separate service injected to manage the cache state, which would be registered as singleton?

**Comment by flatproject** [comment]
@HaoK #176 is definitely sufficient for what i'm doing and a good replacement for V1.1 IOptionsSnapshot functionality.

I also like @dazinator @MaKCbIMKo idea on how to register the cache for options and be able to provide a custom cache implementation as well.

Is there going to be an easy(ier) way to invalidate a specific configuration source cache and reload it?

**Comment by HaoK** [comment]
@flatproject I'm not sure how much easier it will be.  We were hoping that scoped options would be enough for the majority of those cases.  With the more advanced singleton cache with invalidation triggered config reload still possible, but not be the mainline path.

**Comment by HaoK** [comment]
Whelp, not much chance of removing monitor now that logging is going to use it potentially...

https://github.com/aspnet/Logging/pull/626/files
