### ISSUE TITLE
IOptionsSnapshot<> documentation

### ISSUE THREAD

**Issue by Boggin** [aspnet/Options#172]
The API documentation [[https://docs.microsoft.com/en-us/aspnet/core/api/microsoft.extensions.options](https://docs.microsoft.com/en-us/aspnet/core/api/microsoft.extensions.options)] doesn't mention `IOptionsSnapshot<>` at all which is a little confusing. The Interface has /// Xml markup so it should be in the docs. Perhaps an issue for the documentation team but I don't want to cross-post just yet.

**Comment by HaoK** [comment]
@Rick-Anderson

**Comment by Rick-Anderson** [comment]
@danroth27  who owns API? How often is API updated?

**Comment by passuied** [comment]
Agreed! Started to use IOptions<T> because that's what is documented and expecting it to update automatically on reload but when we dug we realized it doesn't (silly behavior really) and had to use IOptionsSnapshot<T> instead which is not documented at all...

**Comment by HaoK** [comment]
It might be best to just update the Options documentation to match where we land for Options 2.0, fairly large changes are happening, bf76cdbf8b3404faa1a1ef0d05225b653b0a4e0b

**Comment by HaoK** [comment]
Filed an issue in docs
