### ISSUE TITLE
[Question] Possibility to make Options immutable?

### ISSUE THREAD

**Issue by dmitry-zaets** [aspnet/Options#181]
First of all, thanks a lot for a great abstraction level around the configuration.

Is there any way to make Options immutable so when they are gets injected they can't be changed?

**Comment by HaoK** [comment]
Do you mean immutable like a ReadOnlyDictionary immutable?  where myOptions.Foo = "Bar" would  throw?

**Comment by dmitry-zaets** [comment]
I would rather expect to have a POCO class without setters in properties. Since Options are using reflection to instantiate the objects, no public setters are needed. Then you will not be able to mutate data from outside.

**Comment by MaKCbIMKo** [comment]
It default case of reading config files and put the values to options object, it will require to change `ConfigurationBinder` class to not look for public setters or provide different way of setting the values.

But how about custom configuration when we can just manually set the value? Here we need a public setters.

I was thinking about using something like proxy-classes. 
e.g. we configuring some POCO. In the core we dynamically create proxy that will be used during all configuration steps. And then, when we will ask for particular options object, then proxy would be converted to initial POCO that might be immutable (or even struct).

But this requires really huge effort and I'm not sure if it's worth.

**Comment by dmitry-zaets** [comment]
Yes, it will require changes of `ConfigurationBinder`.
In the case of manual initialization - you probably can use the constructor with parameters, which will allow you to set up read-only properties.

**Comment by MaKCbIMKo** [comment]
But we might have a few steps of initialization. It means that we create the instance at first and then apply all configurations that we need.

**Comment by dmitry-zaets** [comment]
Few steps are fine, just use immutable flow (recreate new instances if change is needed)

**Comment by HaoK** [comment]
So you are free to make your POCOs immutable in this way (readonly properties with private setter), once we add the ability to bind to private/internal setters in https://github.com/aspnet/Configuration/issues/394

**Comment by MaKCbIMKo** [comment]
Readonly properties with private setters will work only for `ConfigurationBinder` - there we are able to set any property because of reflection.

But how about custom configuration options (e.g. by custom `Action`) ? `private` won't let to modify that. `internal` will keep the way to change the property.

**Comment by HaoK** [comment]
Yeah so my point is that once we support binding to all properties with any kind of setter, there's a way to accomplish what he wants, its unlikely we are going to add anything to support this at the options level.

**Comment by MaKCbIMKo** [comment]
What I was thinking about like a solution is that having some proxy class (not sure about implementation) for each TOptions that will allow to set any properties during configuration, but not allowing using setters in all other places. In the meantime, I still would like to create a simple POCO classes. The main problem is how to create such proxy class.

**Comment by HaoK** [comment]
We will support this via binder https://github.com/aspnet/Configuration/issues/394
