### ISSUE TITLE
Possibly undesirable dependency?

### ISSUE THREAD

**Issue by ddurschlag** [aspnet/Options#184]
In general, I've found that Microsoft.Extensions.* are nicely separated projects, and any coupling is to Microsoft.Extensions.*.Abstractions. I'm pretty happy with this. This project, however, depends on Microsoft.Extensions.Configuration.Binder, which depends on Microsoft.Extensions.Configuration. It this necessary/desirable? See https://github.com/aspnet/Options/blob/dev/src/Microsoft.Extensions.Options.ConfigurationExtensions/Microsoft.Extensions.Options.ConfigurationExtensions.csproj#L19 for the actual dependency.

**Comment by HaoK** [comment]
Yup, this package exists soley to add to that dependency when someone wants to bind options to configuration.

**Comment by ddurschlag** [comment]
Alright, intentional then. Is there a general standard on when it is/isn't ok to take a dependency on implementations (as opposed to abstractions) on a different branch of the namespace tree? I'd love to have a better mental model on how these packages lain out.

**Comment by HaoK** [comment]
General idea is to try to avoid taking dependencies on implementations unless its unavoidable, so basically prefer Abstractions whenever possible is the general rule.
