### ISSUE TITLE
Add back Initialize

### ISSUE THREAD

**Issue by HaoK** [aspnet/Options#185]
Add a `Initialize<TOptions>` set of actions which run after Configure, needed for Auth

**Comment by MaKCbIMKo** [comment]
A quick question: Why `Initialize` goes after `Configure`? Does it correlate with principle of least astonishment? By these names, seems like you need to initialize object first and then configure that.

**Comment by HaoK** [comment]
Yeah its a naming issue, I'm open to considering different names if you have any ideas for something clearer that signify's happening after Configure.

**Comment by MaKCbIMKo** [comment]
I suppose, that just switch the names isn't option? :)

How about that:
First step - `Configure` is like a 'rough processing'.
Second step - `Adjust` or `[Fine]tune` for polishing (fine tuning, polishing)

**Comment by HaoK** [comment]
52ab5f16e7c358a27f4affd14da2ef7082d3d6d1
