### ISSUE TITLE
IOptions<T> vs T for default injection

### ISSUE THREAD

**Issue by rhwilburn** [aspnet/Options#186]
It strikes me that it is not always sensible to inject ` IOptions<T>`

 where as a consumer of Asp.net core I really intend T to be injected most of the time. This leads me to be unwrapping the IOptions instance to get intended type.

Example:

```
public class HomeController : Controller  
{
    private MySettings _settings;
    public HomeController(IOptions<MySettings> settings)
    {
        _settings = settings.Value
    }
}
```

Could become:

```
public class HomeController : Controller  
{
    private MySettings _settings;
    public HomeController(MySettings settings)
    {
        _settings = settings;
    }
}
```
Im sure that sometimes injecting all options makes sense sometimes, but most of the time the user probably is just interested in specific options. Honoring an injectable T into a controller constructor for example would make unit testing easier too and dependencies are more obvious.

Is this something that the community would be on-board me making a change set for? I have code that works for me in my local which is additive to the framework as a work around, but that code is additional to the default behavior of the framework and feels like it should/could be part of the framework.

I am interested in hearing pros and cons on this idea in the comments below. I imagine there were design considerations behind IOptions that I am not considering here with this suggestion?

Moved here from: #2010 in the aspnet master repo

**Comment by rhwilburn** [comment]
This is my work around currently for this scenario:

`builder.Register(ctx => ctx.Resolve<IOptions<MySettings>>().Value);`

This is using Autofac, but I believe that this could be something implicitly bound as part of the framework.

**Comment by davidfowl** [comment]
Digging into the archives https://github.com/aspnet/Options/pull/116

**Comment by davidfowl** [comment]
Here's the issue https://github.com/aspnet/Options/issues/122

**Comment by MaKCbIMKo** [comment]
Sometimes I want to inject just POCO. But sometimes I want to inject wrapped object with some specific functionality (e.g. to be able to reload options within long-running job)

Just went through the issue (https://github.com/aspnet/Options/issues/122).
And I've got a question: why that might be required to use 'default' options EVEN without being registered. I thing that exception should be thrown when I'm trying to use something that wasn't configured.

**Comment by HaoK** [comment]
We don't plan on doing this ever ourselves, but you can always register a func that resolves `T => IOptions<T>` in your container.
