### ISSUE TITLE
Consider implementing IOptionsMonitor in OptionsWrapper

### ISSUE THREAD

**Issue by pakrym** [aspnet/Options#200]
Possibly IOptionsFactory and IOptionsSnapshot too.
Idea is to be able to pass constant options to any options consumer without requiring to implement proxy class (https://github.com/aspnet/Logging/blob/2b6d34778b013908f6d9208b8a69a8286dceac34/test/Microsoft.Extensions.Logging.AzureAppServices.Test/OptionsWrapperMonitor.cs)

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2391
