### ISSUE TITLE
IOptionsMonitor should be updated for 2.0

### ISSUE THREAD

**Issue by HaoK** [aspnet/Options#201]
Related https://github.com/aspnet/Options/issues/199

Snapshot shouldn't responsible for registering IOptionsChangeTokenSource

I think we need to update IOptionsMonitor to use the new 2.0 functionality especially now that logging uses it.

Proposed changes for `IOptionsMonitor` 
- Use IOptionsFactory / support names / post configures
- Use the IOptionsCache to get live updates / handle cache invalidations (should potentially revisit the config reload token hookup to see if there's any improvements there)

@ajcvickers @divega thoughts?  With logging using options monitor, its gone from not very important to super important scenario, and it got 0 love in 2.0 so far...

**Comment by HaoK** [comment]
Note: if we don't end up updating IOptionsMonitor to use IOptionsCache in 2.0, we should remove the public  IOptionsCache since it won't be used anywhere now that Snapshot isn't using it. cc @pakrym

**Comment by divega** [comment]
@HaoK I like the idea because if I understand correctly this also helps making things more consistent across all options flavors. It adds to the work that you need to do for 2.0, and I am not sure if that is a good idea :smile:

**Comment by HaoK** [comment]
@divega and I chatted and we're going to try and make options consistent for 2.0.

IOptions/IOptionsMonitor should both switch to using IOptionsFactory to pickup IPostConfigureOptions.

We should support named options at a minimum for IOptionsMonitor and maybe IOptions if I have time

**Comment by HaoK** [comment]
50a900bbb01690463db0a4aa4ce755bb7c7100e1
