### ISSUE TITLE
IOptionsMonitor is singleton but listener registration is not thread safe

### ISSUE THREAD

**Issue by pakrym** [aspnet/Options#204]
Bad things might happen if two consumers subscribe concurrently. 
Also if subscription happens during invocation.
/cc @HaoK

**Comment by HaoK** [comment]
Yuck, yup not threadsafe

**Comment by HaoK** [comment]
Discussed with @ajcvickers will fix with either using a `SynchronizedCollection` or explicit locks

**Comment by pakrym** [comment]
You can also use `event` internally it is already synchronized.

**Comment by HaoK** [comment]
Good idea, this is pretty much the exact usage pattern for events...

**Comment by HaoK** [comment]
ff4200632970c53a3a6c860219d10477d74060d6
