### ISSUE TITLE
Named support for IOptions (INamedOptions)

### ISSUE THREAD

**Issue by HaoK** [aspnet/Options#207]
Since we don't want to break IOptions, we should add `TOptions INamedOptions.Get(string name)`.

We can do this in 2.1 as well since its not a breaking change.

**Comment by ajcvickers** [comment]
If it's not a breaking change, then 2.1.

**Comment by HaoK** [comment]
We might actually not need a separate interface for this, since IOptionsMonitor is effectively singleton options + names + cache invalidation, so if they want singleton with names, they can just use IOptionsMonitor (and ignore the caching behavior)
