### ISSUE TITLE
Regression: static options snapshots are no longer correctly cached

### ISSUE THREAD

**Issue by PinpointTownes** [aspnet/Options#211]
When https://github.com/aspnet/Options/issues/199 was fixed, you guys opted for making the options snapshots scoped, which introduced a terrible regression.

Now, configuration delegates are run for every authentication handler and for every request, which has both performance and functional implications in ASP.NET Core projects like the OIDC client middleware and community projects like the OIDC server I develop.

Please revert this design change.

More context:

  - https://github.com/aspnet/Security/pull/1065#issuecomment-271478610
  - https://github.com/aspnet/Security/pull/1065#issuecomment-271480850

**Comment by HaoK** [comment]
This wasn't a regression on the options side, this was intentional to make snapshots scoped, Monitor/IOptions are singletons, the issue tracking whether security should be switch to monitor is here: https://github.com/aspnet/Security/issues/1282

**Comment by PinpointTownes** [comment]
Call that intentional if you want, but it impacts even built-in ASP.NET Core components like the OIDC middleware, that has to retrieve the configuration metadata before each OIDC operation (login, logout, etc.) before the `ConfigurationManager` can't be shared.

It worked fine in preview1. For me, it's clearly a regression, no matter who's responsible of it.

**Comment by HaoK** [comment]
There's no test contract today, we don't have any tests that depend on this behavior in Security, if its indeed a causes functional failures as opposed to perf issues, we need to have tests that enforce this.  

@Tratcher does OIDC configuration require reusing the same configuration instances, or can each request recreate these?

**Comment by ajcvickers** [comment]
@Eilon Copying you per discussion today.
