### ISSUE TITLE
OptionsWrapper throws NotImplementedException in `Add` and `Remove`

### ISSUE THREAD

**Issue by cwe1ss** [aspnet/Options#215]
I've seen that [OptionsWrapper.cs](https://github.com/aspnet/Options/blob/dev/src/Microsoft.Extensions.Options/OptionsWrapper.cs) currently throws a `NotImplementedException` in `Add` and `Remove`.

It seems like these are new methods in 2.0 so I'm wondering if they are here by mistake? If not, shouldn't they throw a `NotSupportedException`?

**Comment by HaoK** [comment]
Yeah those look to be methods that got added accidentally by VS, they aren't implementing any interface methods and can be removed
