### ISSUE TITLE
Overload Configure with access to IServiceProvider

### ISSUE THREAD

**Issue by couven92** [aspnet/Options#218]
IServiceCollection support adding ServiceDescriptors with a factory func, rather than an actual instance. It would be helpful, if Configure<TOptions>() would provide an overload where the IConfiguration instance is obtained from the serviceProvider. Currently you cannot configure options when you do not have access to the IConfiguration instance when you call Configure<TOptions>(). This might be the case if you have the IConfiguration stored in the DI container.

**Comment by couven92** [comment]
Proposed solution: https://github.com/aspnet/Options/pull/219

**Comment by tuespetre** [comment]
@couven92 with 2.0 at least, and using the `WebHostBuilder`, the `ConfigureServices` method of `WebHostBuilder` has an overload that can receive a `WebHostBuilderContext` that exposes the `Configuration`.

**Comment by shirhatti** [comment]
Implement `IConfigureOptions` instead of calling `.Configure()`
Your concrete implementation can depend on whatever services you need including `IServiceProvider`
