### ISSUE TITLE
Inconsistent use of null vs DefaultName

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Options#220]
With introduction of named options there are a series of APIs that require you to pass in the name of your instance. However, there is inconsistent behavior for working with the default instance. E.g. `IOptionsFactory<T>.Create(name)` accepts `null` to create the default instance, but `IOptionsMonitor<T>.TryRemove(name)` throws for null and requires you to use `Options.DefaultName` for the default instance.  Decide if nulls are allowed or not, but be consistent. If they are, then silently map to DefaultName as appropriate.

**Comment by HaoK** [comment]
We should probably relax things and just use the default name instead of throwing anywhere when a null name is specified.  

Note we do use null name in a few cases to mean ignore the name, and target all named instances (i.e. ConfigureNamedOptions)
