### ISSUE TITLE
IConfigureOptions isn't called for authentication (named) options

### ISSUE THREAD

**Issue by khellang** [aspnet/Options#225]
After a [Twitter discussion](https://twitter.com/ythos/status/898288736173137920) with @mwadams, we discovered this weird thing...

The `OptionsFactory.Create` method seems to only call registered `IConfigureOptions<T>` when `name == Options.DefaultName`:

https://github.com/aspnet/Options/blob/e71178f68728a023495810c1ab9d463f8142c760/src/Microsoft.Extensions.Options/OptionsFactory.cs#L28-L47

This results in `IConfigureOptions<T>` not being called when options are requested from authentication handlers (or any other named options):

https://github.com/aspnet/Security/blob/488eb44467eb677eab62bdc49aa6255cc1be3119/src/Microsoft.AspNetCore.Authentication/AuthenticationHandler.cs#L89

Why is this? Was this intended or a regression? It seems like a weird, artificial restriction to have. Not to mention the inconsistently configured named/default options you'd have around.

A workaround is to just use the exact same class, but implement `IPostConfigureOptions<T>` instead.

// @HaoK (from commit https://github.com/aspnet/Options/commit/52ab5f16e7c358a27f4affd14da2ef7082d3d6d1)

**Comment by mwadams** [comment]
The 1.1 behaviour was for this to be called for all handlers.

**Comment by HaoK** [comment]
Yes Auth 2.0 uses named options, IConfigureOptions are equivalent to IConfigureNamed options with name = Options.DefaultName

**Comment by HaoK** [comment]
IPostConfigureOptions works because it supports names since its new in 2.0, we wanted to preserve existing behavior for existing users of IOptions/IConfigureOptions so we left those alone and added IConfigureNamedOptions.

**Comment by HaoK** [comment]
You need to switch to IConfigureNamedOptions to be able to target the correct authentication scheme in 2.0, this breaking change was intentional

**Comment by HaoK** [comment]
I added this to the known issues at the bottom of the Auth 2.0 announcement: https://github.com/aspnet/Announcements/issues/262

**Comment by khellang** [comment]
Alright. I think we're done here 👍
