### ISSUE TITLE
[Question] Get Options immediately after Configure

### ISSUE THREAD

**Issue by billpratt** [aspnet/Options#226]
I have a need for configure options to be accessed via DI as well as needing them right away to do some additional configuration. Below is what I have so far. Is this right? Is there a better way? Am I way off? 

```csharp
var section = configuration.GetSection("CacheSettings");
services.Configure<CacheSettings>(section);

var cacheSettings = section.Get<CacheSettings>();

if(cacheSettings.Use.....)
```

Is there a way to do this instead?

```csharp
var section = configuration.GetSection("CacheSettings");
var cacheSettings = section.Get<CacheSettings>();

services.Configure<CacheSettings>(cacheSettings);
```

**Comment by HaoK** [comment]
Can you clarify what you are trying to do exactly?

It looks like you are trying to store some settings in configuration, and binding them to your options, which should work fine.  You also want to tweak the options after reading the initial settings from config?

That should work fine as well, what isn't working for you?

**Comment by billpratt** [comment]
@HaoK Everything is working fine. I was wondering if there was a better way. Since I'm creating the cache settings to use locally, it would be nice to have an overload that takes in an instance of the type I'm configuring in DI.

Something like...
```
var section = configuration.GetSection("CacheSettings");
var cacheSettings = section.Get<CacheSettings>();

services.Configure<CacheSettings>(cacheSettings);
```

**Comment by HaoK** [comment]
If you really want to avoid that hit, you can always do some kind of nesting:

```
class CacheOptions {
   public CacheSettings Settings { get; set; }
}
```

Then `services.Configure<CacheOptions>(o => o.Settings = cacheSettings)`

**Comment by HaoK** [comment]
Or you can always just hammer in the options instance as a singleton wrapped in IOptions: `services.AddSingleton<IOptions<CacheSettings>>(Options.Create(cacheSettings))`

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2389
