### ISSUE TITLE
See if we can make it easier to implement IConfigureNamedOptions

### ISSUE THREAD

**Issue by HaoK** [aspnet/Options#229]
Today you have to implement both IConfigureOptions and the similar name overload, and its easy to do incorrectly, i.e. registering `services.AddScoped<IConfigureNamedOptions>` instead of `services.AddScoped<IConfigureOptions>`

**Comment by davidfowl** [comment]
@shirhatti was this done? How is this a task?

**Comment by shirhatti** [comment]
Consensus in the room was let's close this issue. "_Fowler will hunt us down if he still cares about it_."
