### ISSUE TITLE
Revisit by-convention options from configuration

### ISSUE THREAD

**Issue by divega** [aspnet/Options#23]
@Eilon has expressed some concerns with the "amount of magic" in the current design that pulls configuration information into an instance of an options type `MyOptions` through a call to `services.Configure<MyOptions>(configuration)`, and on how this is currently used across the frameworks. Filing this issue to track that so that we can have a follow up conversation.

**Comment by HaoK** [comment]
This is currently broken again, along with service replacement due to frameworks calling Add on their dependencies, i.e. Options, DataProtection, etc.

**Comment by HaoK** [comment]
@davidfowl suggested that we just cut all automatic Configure options from any AddXyz methods, users can always manually call services.ConfigureXyz(config) to bind options to config.  I will make a pass once builds are stable and remove Configuration from all AddXyz methods that do not need them

**Comment by HaoK** [comment]
Removed options from AddXyz methods
