### ISSUE TITLE
DI exception is not raised when IOptions<Poco> is not configured.

### ISSUE THREAD

**Issue by robertbaker** [aspnet/Options#242]
When using DI and injecting options, if you fail to configure the option in the startup.cs, no exception is raised.

The options.Value property is null, which may throw an exception at runtime.

This is dangerous as you have no safety when using IOptions, there needs to be a way for the DI system to crash on startup if IOptions<POCO> is not configured in startup.cs. This goes against expectations, any other dependency that isn't registered in the DI container will cause an exception on startup,

**Comment by HaoK** [comment]
IOptions have a new() constraint on TOptions, so if you don't configure them, its by design that you end up with a new TOptions().

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2384
