### ISSUE TITLE
IOptionsSnapshot is not working with singleton services

### ISSUE THREAD

**Issue by ductrantb** [aspnet/Options#247]
Hi friends,
I have a problem with IOptionsSnapshot. I was tried to use BackgroundServiceManagerConfigsFactory as a transient service to renew configs on change.
```
services.AddTransient<BackgroundServiceManagerConfigsFactory, BackgroundServiceManagerConfigsFactory>();
services.AddSingleton<BackgroundServiceManager, BackgroundServiceManager>();
```

The constructor of my configs factory was called on every request (by singleton service), but configs value was not changed.

```
public BackgroundServiceManagerConfigs Configs { get; protected set; }
public BackgroundServiceManagerConfigsFactory(IOptionsSnapshot<BackgroundServiceManagerConfigs> options)
{
        Configs = options.Value;
}
```
I tried to call this factory in a controller, it worked.
I used netcore 2.0 and Microsoft.Extensions.Options version 2.0.0.0
Thank you.

**Comment by aspnet-hello** [comment]
This issue was moved to aspnet/Home#2380
