### ISSUE TITLE
Rename IOptions<TOptions>.Options to .Value

### ISSUE THREAD

**Issue by davidfowl** [aspnet/Options#31]
Normally, you declare variables like this:

```C#
public class Foo
{
     private MyOptions _options;
     public Foo(IOptions<MyOptions> options)
     {
        _options = options.Value;
     }
}
```

**Comment by HaoK** [comment]
@davidfowl @lodejard @divega with Named options being removed (soon), should we go back to IOptionsAccessor to match IHttpContextAccessor?

Or keep it IOptions and just switch it to IOptions.Value?

**Comment by HaoK** [comment]
Options are meant to be simple poco data objects. I believe the motivations are similar to why configuration is not put into DI. But the actual initialization of options(IConfigureOptions) are.

**Comment by brockallen** [comment]
But `IOptions<T>`, in effect, is putting options into DI. I guess I don't understand the difference.

**Comment by HaoK** [comment]
@divega @davidfowl What do you guys think about renaming IOptions to ISharedOptions to convey that this is meant to be used mostly when options are singletons/shared... 

ISharedOptions.Value would be its only property.

**Comment by lodejard** [comment]
Lets keep the name IOptions<T>. It started out as IOptionsAccessor which was inconveniently verbose.

@brockallen it is very similar, but the accessor service has advantages in that the creation of the singleton is deferred to when it's first used. Plus it enables the pattern where multiple IConfigureOptions<TOptions> can be added as services to alter any given TOptions. With a singleton MyOptions added to DI it must be fully baked before it is added, and the things doing the options configuration all need to do their work before IOC is available.

**Comment by HaoK** [comment]
c623fbc3c6a8b037ed191da950587d6fa884bcac
