### ISSUE TITLE
Consider supporting arrays

### ISSUE THREAD

**Issue by gingters** [aspnet/Options#56]
I could PR support for array types, if desired, based on what I did in my ConfigurationMapper: https://github.com/gingters/SmartDev.ConfigurationMapper/blob/dev/src/SmartDev.ConfigurationMapper/ValueTypeConverter.cs

Any interest in array support? If yes I'll prepare a PR.

**Comment by davidfowl** [comment]
Configuration actually doesn't; support arrays currently. Discussion here https://github.com/aspnet/Configuration/issues/115

**Comment by gingters** [comment]
Pretty much no input format except JSON does support arrays there.
The question would be more, would you treat specially formatted values (i.e. comma separated values) as an array and simply de-serialize these into an array?

**Comment by victorhurdugaci** [comment]
Fixed in https://github.com/aspnet/Options/pull/59
