### ISSUE TITLE
BCL API review: Consider decoupling options from DI

### ISSUE THREAD

**Issue by divega** [aspnet/Options#70]
Options was designed to work well with DI, but the only part that really depends directly on DI is the extension methods on `IServiceCollection`: `Configure()` and `AddOptions()`. The idea with this issue is propose we separate those extension methods into a different package from the core of Options which in theory could be used independently of DI, e.g. using code generation.

**Comment by HaoK** [comment]
There isn't much left in options with the binder moving to Config
