### ISSUE TITLE
Consider adding the Action-property to the IConfigureOptions-interface.

### ISSUE THREAD

**Issue by mausworks** [aspnet/Options#72]
At the current state, the `IConfigureOptions`-interface does not contain the `Action`-property.
But the `ConfigureOptions`-class does.

Since the `Configure<T>`-extension adds the options as a `IConfigureOptions<T>` to the service-collection, casts have to be made in order to utilize the `Action`-property, which is needed to properly implement the options.

Adding the property to the `IConfigureOptions`-interface would make for smoother implementations.

Here is an example of what i mean:
https://github.com/mausworks/MausWorks.MongoDB-Service/blob/master/MongoDBContextProvider.cs#L38,L53

Called from:
https://github.com/rausmaus/MausWorks.MongoDB-Service/blob/master/DependencyInjection/MongoDBServiceCollectionExtensions.cs#L83-L88

I might be wrong in my approach of doing this; but EntityFramrowk does not use the OptionsModel and it kind of does it the same way.

**Comment by HaoK** [comment]
The options pattern has changed/simplified a bit with the removal of named options, so you should be able to just use `Action<MondoDBContextProviderOptions>`
