### ISSUE TITLE
NeutralResourcesLanguage Warning on UWP

### ISSUE THREAD

**Issue by bricelam** [aspnet/Options#73]
I'm getting the following warning on a Universal Windows App.

> warning MSB3817: The assembly "Microsoft.Framework.OptionsModel.dll" does not have a NeutralResourcesLanguageAttribute on it. To be used in an app package, portable libraries must define a NeutralResourcesLanguageAttribute on their main assembly (ie, the one containing code, not a satellite assembly).

**Comment by Eilon** [comment]
Hmmm... we might want to set that on all our DLLs. We normally have `en-US` embedded in all our "main" DLLs and use satellite resources only for non-`en-US` resources, and so the neutral language is always `en-US`.

**Comment by bricelam** [comment]
:+1: Making it part of KoreBuild would be better than doing it in each of the projects that target dotnet/netcore50.

**Comment by divega** [comment]
@bricelam @muratg given aspnet/Universe#246, is there anything actionable to track here on Options or can this bug be now closed?

**Comment by pranavkm** [comment]
Fixed in https://github.com/aspnet/Options/commit/9902f77b89390733fb38667bfe62f20eff71216b
