### ISSUE TITLE
Consider if Configure<T> should implicitly call AddOptions()

### ISSUE THREAD

**Issue by brockallen** [aspnet/Options#76]
Would make using this one step easier.

**Comment by HaoK** [comment]
In general all of the frameworks that use Options do call this for you, like AddMVC

**Comment by brockallen** [comment]
In general I tend to start with no frameworks :)

**Comment by HaoK** [comment]
Then you are responsible for adding your service dependencies yourself :)

**Comment by brockallen** [comment]
Fair enough. I was just trying to point out that if 90% of the time we're always doing those exact 2 lines of code together, then perhaps it would make more sense consolidated.

**Comment by HaoK** [comment]
Another way to think about it is that Options is itself a framework, so to use it, you need to call AddOptions just like anyone other framework
