### ISSUE TITLE
API Design: make strongly typed settings easier

### ISSUE THREAD

**Issue by jods4** [aspnet/Options#82]
I am lifting some discussion that was briefly started by @brockallen in #31 into its own issue.

I have been using the `IOptions` API for a while now in the context of application settings and it just feels convoluted for no reason. I have the impression that I repeat meaningless, verbose, boilerplate code because... well because the framework wants me to.

Basically, anywhere a component needs to adjust its behaviour based on a setting (typically stored in `config.json`), you see a pattern similar to:
```csharp
class FrobController
{
  private readonly AppSettings settings;

  public FrobController(IOptions<AppSettings> options)
  {
    this.settings = options.Options; // or options.Value in beta-8 I think
  }
 
  public void FrobMe()
  {
    for (int i = 0; i < settings.FrobbingTimes; i++)
      FrobOnce();
  }
}
```

And if you use settings in many places or have split your settings in several classes by domain, you repeat that ctor code quite a lot. What bothers me?

- What the hell is this `IOptions<>`? Vague naming is vague. And it's not the _options_ since they are in `AppSettings`, actually.
- What is it about? Why should I use it? What does it buy me? In this use-case: nothing!
- Given its generic name and its non-existent added value, it's hard to discover. Trust me, the first time you encounter this you try to DI `AppSettings`. And it fails. Then you Google.
- The dance around `.Options` or `.Value` is superfluous.
- The naming is awkward. What should I call the parameter `IOptions`? Any name I could come up with is either long for what it's worth (`optionsAccessor`) or misleading/clashing with the _actual_ options object (`AppSettings`).

In #31 @lodejard said:
> it is very similar, but the accessor service has advantages in that the creation of the singleton is deferred to when it's first used.

Deferred creation is something that needs a general solution, not a domain-specific one. And the solution is injecting `Lazy<T>` and registering a factory for `T`. And given the smallish nature of application settings in general and the fact that they are guaranteed to be used, the lazy initialization is probably more overhead than benefit.

> Plus it enables the pattern where multiple IConfigureOptions can be added as services to alter any given TOptions. 

Maybe for middleware configs or other advanced stuff. I don't see how that would be a use case for application settings. The use-case here is really to parse config into a strongly-typed object and make it available to the whole app.

> With a singleton MyOptions added to DI it must be fully baked before it is added, and the things doing the options configuration all need to do their work before IOC is available.

Not necessarily. Alternative design can surely be considered, like having the "things" mutate the options after the fact, or registering a factory that applies the "things" just in time when creating the actual instance. Anyway I don't see how this is pertinent for app settings.

My point is that probably those things are important for other scenarios (middleware configuration?) but I think the _typed application settings_ use case should be simplified. What feels right is injecting the typed class directly.

**Comment by davidfowl** [comment]
Why do you want to use IOptions in the first place? Are are you saying that you want something else for pocos other than just putting instances in the container?

**Comment by jods4** [comment]
@davidfowl I don't want to use `IOptions`! But I got the impression from the docs that it was the suggested way. 
There are good points, though.
Once you do `app.Configure<AppSettings>(Configuration.GetSection("AppSettings"))`, you're ready to go:
1. The settings are taken from the configuration system (any source you have configured)
2. They are parsed into a strongly typed class for you
3. They are accessible pretty much anywhere with the DI.

I guess I would just like to be able to DI `AppSettings` directly, rather than `IOptions<AppSettings>`, which does not make a whole lot of sense (in this context at least).

Do you suggest another way? 
Previously in ASP.NET, the "way" to do that was a designer in Properties that generated a strongly typed singleton class (usually `MyNamespace.Properties.Settings`).

**Comment by lodejard** [comment]
You're not required to use IOptions if you want to bind an object from config directly... You might need to add dependency on ` "Microsoft.Framework.Configuration.Binder": "1.0.0-*"`. For example:

```csharp
    public class Startup
    {
        private readonly IConfiguration Configuration;

        public Startup(IApplicationEnvironment env)
        {
            Configuration = new ConfigurationBuilder(env.ApplicationBasePath)
                .AddJsonFile("config.json")
                .Build();
        }

        public void ConfigureServices(IServiceCollection services)
        {
            var settings = new MyNamespace.Properties.Settings();
            Configuration.GetSection("appSettings").Bind(settings);
            services.AddInstance(settings);
        }
```

Is that closer to the code you're prefer to have? The settings class can be used as a service or controller dependency directly at that point.

**Comment by divega** [comment]
FWIW, this terser syntax should already work with nightly builds:

``` C#
    var settings = Configuration.Get<MyNamespace.Properties.Settings>("appSettings");
    services.AddInstance(settings);
```

**Comment by jods4** [comment]
@lodejard yes, that would do the trick.
@divega and the new typed `Get`s (very good addition BTW) make it a lot cleaner!

Yet I somehow still believe the method that does those two (or three) lines of code should be in the framework. Maybe `services.AddSettings<AppSettings>("appSettings")`. 
Or just `services.AddSettings<AppSettings>()` and the section name might be in an attribute.

First because application settings is a fundamental thing. Every serious applications needs it. The framework should provide guidance on how to handle them, in an easily discoverable way.

Second, right now the helper method is trivial, that's true. But in the future you might want to include more features:
- transparent encryption (ok that would probably entirely be at the `Configuration` level?)
- save changes (by modifying Settings class directly, not through Configuration)
- live reload (because of thread safety you can't modify the Settings object directly, but you could replace the one in the DI for new services, and if it implements an `ISettingsChanged` interface or something, you could call a notification event so that part of the code that already have the settings may get the new ones).
- decide to merge app-wide settings and user-wide settings (that was in .NET of old times). It's not useful for ASP.NET, but if we start using .NET Core to build cross-platform console applications (or even x-plat UI) then it's needed.

Overall there is a lot of overlap between `Configuration` and what I call `Settings`, so maybe the former should be used for that latter. But currently it's a bit complicated for that.

**Comment by davidfowl** [comment]
@jods4 Seems like your initial problem is solved. If you want to have a more general discussion about configuration or request specific features, I'd suggest opening individual issues.

**Comment by jods4** [comment]
@davidfowl I opened this issue specifically to request simpler API for handling application settings.

I don't have a problem _per se_ as everything works, so if you don't want to pursue this suggestion further feel free to close the issue.

**Comment by davidfowl** [comment]
Great!
