### ISSUE TITLE
Rename Microsoft.Framework.* to Microsoft.Extensions.*

### ISSUE THREAD

**Issue by Eilon** [aspnet/Options#84]
Need to rename assemblies and namespaces from `Microsoft.Framework.*` to `Microsoft.Extensions.*`.

Once the change is committed, please post an issue in the https://github.com/aspnet/Announcements/issues/ repo that links back to this issue.

**Comment by Eilon** [comment]
@HaoK unless you really want to do this, @pranavkm is going to bulk do them all.

**Comment by HaoK** [comment]
Yay I really don't... :)

**Comment by divega** [comment]
:smile:

**Comment by pranavkm** [comment]
3fc0489b3f70a96d1fa4b1b560b52c5e5a23a50d
