### ISSUE TITLE
Review APIs, in particular naming

### ISSUE THREAD

**Issue by divega** [aspnet/Options#86]
We still have a few names in the public surface that are a bit strange. We should do another review.

**Comment by HaoK** [comment]
Is this something you wanted to in RC2?  Doesn't seem like a good idea to wait for RTM for this :)

**Comment by divega** [comment]
Yes, sure!

**Comment by HaoK** [comment]
Were there any other names left that you concerned about?  We updated the reloadable options names already?

**Comment by divega** [comment]
I haven't looked at these for a while. Probably need to do proper API review to answer.

**Comment by HaoK** [comment]
We did this as part of the IOptions/Watcher changes
