### ISSUE TITLE
Thread safety in OptionsManager

### ISSUE THREAD

**Issue by fedotovalex** [aspnet/Options#88]
In the current implementation of OptionsManager, if I do something like this:

```c#
public void ConfigureServices(IServiceCollection services)
{
    services.Configure<MyOptions>(options => {
          // some code, maybe not trivial
    });
}
```

and then later, from multiple threads:

```c#
var options = services.GetRequiredService<IOptions<MyOptions>>().Value;
```

the configuration action may be invoked more than once, which is not intuitively expected.

If this is the desired behavior, it needs to be documented very clearly. Personally, I would prefer the options manager to deal with concurrency issues and guarantee that the configuration action is only invoked once.

**Comment by herecydev** [comment]
Isn't it dangerous to assume any default lifetime? I certainly wouldn't expect that the framework to bind singleton for you. Though wouldn't [this](https://github.com/aspnet/Options/blob/dev/src/Microsoft.Extensions.OptionsModel/OptionsServiceCollectionExtensions.cs#L73) sort out your issue.

**Comment by HaoK** [comment]
By default AddOptions adds OptionsManager as a singleton, so it's only done once in the normal case.

**Comment by divega** [comment]
@HaoK I believe @fedotovalex is referring to the case of two threads (e.g. two concurrent requests) invoking `.Value` concurrently on the same singleton. I just checked and we don't have any concurrency code? Didn't we have that?

**Comment by HaoK** [comment]
ec13249a35bbf1d4a8a381a9697965cc1208fe82
