### ISSUE TITLE
@inject does not work - all fields are always null.

### ISSUE THREAD

**Issue by xatabhk** [aspnet/Options#91]
appsettings.cs:

```c#
   public class AppSettings
    {
        public string SiteTitle { get; set; }
    }
```

appsettings.json:

```json
{
    "AppSettings": {
    "SiteTitle": "ZaxiTech"
  }
```

Startup.cs:

```c#
public static IConfiguration Configuration { get; set; }

services.AddOptions();  // Setup options with DI
services.Configure<AppSettings>(Configuration);
```

xview.cshtml:

```
@using Microsoft.Extensions.OptionsModel
@inject IOptions<AppSettings> MyAppSettings
```

And all fields like SiteTitle in MyAppSettings are always null.

**Comment by PMExtra** [comment]
I have the same problem, have you solved it?

**Comment by davidfowl** [comment]
Try

```
services.Configure<AppSettings>(Configuration.GetSection("AppSettings"));
```

**Comment by PMExtra** [comment]
I got it, @davidfowl is right.
I had read the docs and known "setup the IOptions<TOption> service", but I misspelled the configuration section name >_<...

docs link:
http://docs.asp.net/en/latest/fundamentals/configuration.html#using-options-and-configuration-objects

**Comment by xatabhk** [comment]
@davidfowl 
No. services.Configure<AppSettings>(Configuration.GetSection("AppSettings")) works no more on latest RC2.

But I have found a workaround for this issue as follows:
services.Configure<AppSettings>((xx)=> {
				xx.SiteTitle=Configuration.GetSection("AppSettings")["SiteTitle"];
});

Still, settings are not loaded automatically.

**Comment by davidfowl** [comment]
@xatabhk It does work, the syntax (and namespace) probably changed

**Comment by xatabhk** [comment]
@davidfowl 
Buit it does not work as expected. User has to do property/field mapping manually like this:
xx.SiteTitle=Configuration.GetSection("AppSettings")["SiteTitle"];

**Comment by davidfowl** [comment]
Nah, can you provide the fully non working sample? Pushing to a github repo with instructions would be best.

**Comment by divega** [comment]
@xatabhk the `Configure<T>()` extension methods that take an `IConfiguration` where moved to a new package (Microsoft.Extensions.Options.ConfigurationExtensions) to decouple dependencies. See #97 for more information.
