### ISSUE TITLE
DateTime ConvertFromInvariantString test fail ( as expected )

### ISSUE THREAD

**Issue by devel0** [aspnet/Options#98]
Running unit tests I got fail at  `Configure_GetsNullableOptionsFromConfiguration`  test for given test datetime, this is expected cause the test try to ConvertFromInvariantString at ConfigurationBinder.cs (ReadValue) where passed input string is generated by the OptionsTest.cs(Configure_GetsNullableOptionsFromConfiguration_Data) where a datetime string is generated using current culture instead of the invariant one.
```{ nameof(NullableOptions.MyNullableDateTime), new DateTime(1995, 12, 31).ToString(CultureInfo.CurrentCulture.DateTimeFormat.ShortDatePattern) }```

**Comment by HaoK** [comment]
@divega what behavior do we want here?  Indeed we are always converting from Invariant in the binder, should we try both with Invariant first and then a normal ConvertFromString if the first fails?

**Comment by MichaCo** [comment]
I'd say it is not a good idea to parse with the current culture. Instead, this test should be fixed with setting the culture correctly.

What would happen if you have a date string formatted with the `de-DE` culture in your configuration and deploy that to production where the culture is `en-US`? Yup it would fail...
*runs on my machine* issue :crying_cat_face:

**Comment by HaoK** [comment]
Yeah I guess what we have is fine, its just a test issue, and invariant string format is the only supported one

**Comment by HaoK** [comment]
@divega is it expected that we need to support running our tests outside of en-US?  Either way the priority of this should be low as its not causing any issues unless you run tests with a different culture... Moving to backlog

**Comment by HaoK** [comment]
758e11ecee0c30e12d3498182a799148d7d45a8c

**Comment by divega** [comment]
Also, I have filed https://github.com/aspnet/Configuration/issues/348 to follow up on what behavior we want on the product re culture.
